// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"auth-svc/api/auth"
)

type ControllerAuth struct{}

func NewAuth() auth.IAuthAuth {
	return &ControllerAuth{}
}
