# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(localhost:3306)/cinemahouse_db"
        tables: "room_type,seat_type,movie_type,ticket_price,cinema,movie,payment,screening_room,screening_session,seat,bill,ticket,movie_typeofmovies"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
