// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cinema

import (
	"cinemahouse-svc/api/cinema"
)

type ControllerCinema struct{}

func NewCinema() cinema.ICinemaCinema {
	return &ControllerCinema{}
}
