// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package movie

import (
	"cinemahouse-svc/api/movie"
)

type ControllerMovie struct{}

func NewMovie() movie.IMovieMovie {
	return &ControllerMovie{}
}
