// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package payment

import (
	"cinemahouse-svc/api/payment"
)

type ControllerPayment struct{}

func NewPayment() payment.IPaymentPayment {
	return &ControllerPayment{}
}
