// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package booking

import (
	"cinemahouse-svc/api/booking"
)

type ControllerBooking struct{}

func NewBooking() booking.IBookingBooking {
	return &ControllerBooking{}
}
