// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"auth-svc/internal/dao/internal"
)

// invalidatedTokensDao is the data access object for the table invalidated_tokens.
// You can define custom methods on it to extend its functionality as needed.
type invalidatedTokensDao struct {
	*internal.InvalidatedTokensDao
}

var (
	// InvalidatedTokens is a globally accessible object for table invalidated_tokens operations.
	InvalidatedTokens = invalidatedTokensDao{internal.NewInvalidatedTokensDao()}
)

// Add your custom methods and functionality below.
