// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"auth-svc/internal/dao/internal"
)

// rolePermissionsDao is the data access object for the table role_permissions.
// You can define custom methods on it to extend its functionality as needed.
type rolePermissionsDao struct {
	*internal.RolePermissionsDao
}

var (
	// RolePermissions is a globally accessible object for table role_permissions operations.
	RolePermissions = rolePermissionsDao{internal.NewRolePermissionsDao()}
)

// Add your custom methods and functionality below.
