// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"auth-svc/api/user"
)

type ControllerUser struct{}

func NewUser() user.IUserUser {
	return &ControllerUser{}
}
