# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(localhost:3306)/auth_db"
        tables: "invalidated_tokens,permission,role,comment,user,user_roles,role_permissions"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true