// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// billDao is the data access object for the table bill.
// You can define custom methods on it to extend its functionality as needed.
type billDao struct {
	*internal.BillDao
}

var (
	// Bill is a globally accessible object for table bill operations.
	Bill = billDao{internal.NewBillDao()}
)

// Add your custom methods and functionality below.
