// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// cinemaDao is the data access object for the table cinema.
// You can define custom methods on it to extend its functionality as needed.
type cinemaDao struct {
	*internal.CinemaDao
}

var (
	// Cinema is a globally accessible object for table cinema operations.
	Cinema = cinemaDao{internal.NewCinemaDao()}
)

// Add your custom methods and functionality below.
