// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// movieTypeofmoviesDao is the data access object for the table movie_typeofmovies.
// You can define custom methods on it to extend its functionality as needed.
type movieTypeofmoviesDao struct {
	*internal.MovieTypeofmoviesDao
}

var (
	// MovieTypeofmovies is a globally accessible object for table movie_typeofmovies operations.
	MovieTypeofmovies = movieTypeofmoviesDao{internal.NewMovieTypeofmoviesDao()}
)

// Add your custom methods and functionality below.
