// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// movieTypeDao is the data access object for the table movie_type.
// You can define custom methods on it to extend its functionality as needed.
type movieTypeDao struct {
	*internal.MovieTypeDao
}

var (
	// MovieType is a globally accessible object for table movie_type operations.
	MovieType = movieTypeDao{internal.NewMovieTypeDao()}
)

// Add your custom methods and functionality below.
