// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// movieDao is the data access object for the table movie.
// You can define custom methods on it to extend its functionality as needed.
type movieDao struct {
	*internal.MovieDao
}

var (
	// Movie is a globally accessible object for table movie operations.
	Movie = movieDao{internal.NewMovieDao()}
)

// Add your custom methods and functionality below.
