// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// paymentDao is the data access object for the table payment.
// You can define custom methods on it to extend its functionality as needed.
type paymentDao struct {
	*internal.PaymentDao
}

var (
	// Payment is a globally accessible object for table payment operations.
	Payment = paymentDao{internal.NewPaymentDao()}
)

// Add your custom methods and functionality below.
