// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// roomTypeDao is the data access object for the table room_type.
// You can define custom methods on it to extend its functionality as needed.
type roomTypeDao struct {
	*internal.RoomTypeDao
}

var (
	// RoomType is a globally accessible object for table room_type operations.
	RoomType = roomTypeDao{internal.NewRoomTypeDao()}
)

// Add your custom methods and functionality below.
