// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// screeningSessionDao is the data access object for the table screening_session.
// You can define custom methods on it to extend its functionality as needed.
type screeningSessionDao struct {
	*internal.ScreeningSessionDao
}

var (
	// ScreeningSession is a globally accessible object for table screening_session operations.
	ScreeningSession = screeningSessionDao{internal.NewScreeningSessionDao()}
)

// Add your custom methods and functionality below.
