// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// screeningRoomDao is the data access object for the table screening_room.
// You can define custom methods on it to extend its functionality as needed.
type screeningRoomDao struct {
	*internal.ScreeningRoomDao
}

var (
	// ScreeningRoom is a globally accessible object for table screening_room operations.
	ScreeningRoom = screeningRoomDao{internal.NewScreeningRoomDao()}
)

// Add your custom methods and functionality below.
