// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// seatDao is the data access object for the table seat.
// You can define custom methods on it to extend its functionality as needed.
type seatDao struct {
	*internal.SeatDao
}

var (
	// Seat is a globally accessible object for table seat operations.
	Seat = seatDao{internal.NewSeatDao()}
)

// Add your custom methods and functionality below.
