// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// seatTypeDao is the data access object for the table seat_type.
// You can define custom methods on it to extend its functionality as needed.
type seatTypeDao struct {
	*internal.SeatTypeDao
}

var (
	// SeatType is a globally accessible object for table seat_type operations.
	SeatType = seatTypeDao{internal.NewSeatTypeDao()}
)

// Add your custom methods and functionality below.
