// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// ticketDao is the data access object for the table ticket.
// You can define custom methods on it to extend its functionality as needed.
type ticketDao struct {
	*internal.TicketDao
}

var (
	// Ticket is a globally accessible object for table ticket operations.
	Ticket = ticketDao{internal.NewTicketDao()}
)

// Add your custom methods and functionality below.
