// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cinemahouse-svc/internal/dao/internal"
)

// ticketPriceDao is the data access object for the table ticket_price.
// You can define custom methods on it to extend its functionality as needed.
type ticketPriceDao struct {
	*internal.TicketPriceDao
}

var (
	// TicketPrice is a globally accessible object for table ticket_price operations.
	TicketPrice = ticketPriceDao{internal.NewTicketPriceDao()}
)

// Add your custom methods and functionality below.
