// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"auth-svc/api/admin"
)

type ControllerAdmin struct{}

func NewAdmin() admin.IAdminAdmin {
	return &ControllerAdmin{}
}
